# Generated by Django 6.0 on 2025-12-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label_type', models.CharField(choices=[('event', 'Event'), ('category', 'Kategorie')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Hauptbild für das Rezept', null=True, upload_to='recipes/')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Gesamtdauer des Rezepts in Minuten', null=True)),
                ('temperature_celsius', models.PositiveIntegerField(blank=True, help_text='Back-/Ofentemperatur in °C', null=True)),
                ('ingredients', models.CharField()),
                ('steps', models.CharField()),
                ('labels', models.ManyToManyField(blank=True, to='recipes.label')),
            ],
        ),
    ]
