# Generated by Django 6.0 on 2025-12-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(help_text='Zutaten'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Label', to='recipes.label'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(help_text='Portionen'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(help_text='Anleitung'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='Titel', max_length=200),
        ),
    ]
