# Generated by Django 6.0 on 2026-01-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredients_alter_recipe_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='working_time',
            field=models.PositiveIntegerField(blank=True, help_text='Arbeitsdauer des Rezepts in Minuten', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Hauptbild', null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='temperature_celsius',
            field=models.PositiveIntegerField(blank=True, help_text='Back-/Ofentemperatur in °C (Ober-/Unterhitze)', null=True),
        ),
    ]
