# Generated by Django 6.0 on 2026-01-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_working_time_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooked_count',
            field=models.PositiveIntegerField(default=0, help_text='So oft wurde das Rezept schon gekocht'),
        ),
    ]
