# Generated by Django 6.0 on 2026-01-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_weeklyplan_weeklyplanentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='external_link',
            field=models.URLField(blank=True, help_text='Fügen Sie einen externen Link hinzu.', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(help_text='Zutaten', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(help_text='Anleitung', max_length=1000),
        ),
    ]
