# Generated by Django 6.0 on 2026-01-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_external_link_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(blank=True, help_text='Zutaten', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(blank=True, help_text='Portionen', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(blank=True, help_text='Anleitung', max_length=1000, null=True),
        ),
    ]
