# Generated by Django 6.0 on 2026-01-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_ingredients_alter_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplanentry',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
