# Generated by Django 6.0 on 2026-01-17 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_weeklyplanentry_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyplanentry',
            options={'ordering': ['date', 'id']},
        ),
        migrations.RemoveField(
            model_name='weeklyplanentry',
            name='day',
        ),
        migrations.AddField(
            model_name='weeklyplanentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
